In [1]:
import cv2
import numpy as np

In [4]:

img=cv2.imread("C:\\Users\\user\\Desktop\\CV\\id.jpg")
img2=cv2.imread("C:\\Users\\user\\Desktop\\CV\\idw.jpg")

In [3]:
r=3/img.shape[2] #height                            #RESIZING THE LOADED IMAGE
print(r)
dim=(4,int(img.shape[2]*r)) #width


r2=400/img2.shape[2]                            #RESIZING THE LOADED IMAGE
print(r2)
dim2=(400,int(img2.shape[2]*r2))


AttributeError: 'NoneType' object has no attribute 'shape'

In [4]:
resized_img=cv2.resize(img,dim,interpolation=cv2.INTER_AREA)          #STORING AND DISPLAYING THE RESIZED IMAGE
resized_img2=cv2.resize(img2,dim2,interpolation=cv2.INTER_AREA)
cv2.imshow("RESIZED ONE ID",resized_img)
cv2.imshow("RESIZED ONE IDW",resized_img2)
cv2.waitKey()

cv2.destroyAllWindows()
                                     

In [5]:
resized_img.shape


(3, 4, 3)

In [6]:
print(resized_img)
np.mean(resized_img,axis=0)  ## finding the mean

[[[184 206 169]
  [191 196 156]
  [189 200 161]
  [184 206 171]]

 [[169 205 164]
  [170 161 141]
  [172 166 144]
  [172 204 166]]

 [[156 196 153]
  [145 163 146]
  [146 166 149]
  [153 189 151]]]


array([[169.66666667, 202.33333333, 162.        ],
       [168.66666667, 173.33333333, 147.66666667],
       [169.        , 177.33333333, 151.33333333],
       [169.66666667, 199.66666667, 162.66666667]])

In [7]:
print(resized_img2)
np.mean(resized_img2)  ## finding the mean

[[[ 62  83 100]
  [ 63  86 102]
  [ 65  88 104]
  ...
  [ 78  98 115]
  [ 76  96 114]
  [ 77  99 117]]

 [[ 67  87 104]
  [ 66  86 103]
  [ 66  86 103]
  ...
  [ 78  98 115]
  [ 79 100 118]
  [ 79 101 119]]

 [[ 70  92 108]
  [ 68  89 106]
  [ 69  89 106]
  ...
  [ 74  93 110]
  [ 75  96 113]
  [ 73  95 112]]

 ...

 [[ 45  41  62]
  [ 53  42  61]
  [ 65  45  61]
  ...
  [ 64  80  96]
  [ 65  81  97]
  [ 65  81  98]]

 [[ 24  31  55]
  [ 32  34  58]
  [ 44  37  59]
  ...
  [ 71  86 102]
  [ 70  86 102]
  [ 68  84 101]]

 [[ 12  21  49]
  [ 15  24  52]
  [ 19  24  51]
  ...
  [ 54  68  84]
  [ 60  74  90]
  [ 66  81  98]]]


192.121

In [8]:

resized_img2.shape

(400, 400, 3)

In [9]:
print("THIS IS THE MATRIX OF ID")
print('\n')
print(resized_img)
print('\n')
print("THIS IS THE MATRIX OF IDW")
print('\n')
print(resized_img2)

THIS IS THE MATRIX OF ID


[[[184 206 169]
  [191 196 156]
  [189 200 161]
  [184 206 171]]

 [[169 205 164]
  [170 161 141]
  [172 166 144]
  [172 204 166]]

 [[156 196 153]
  [145 163 146]
  [146 166 149]
  [153 189 151]]]


THIS IS THE MATRIX OF IDW


[[[ 62  83 100]
  [ 63  86 102]
  [ 65  88 104]
  ...
  [ 78  98 115]
  [ 76  96 114]
  [ 77  99 117]]

 [[ 67  87 104]
  [ 66  86 103]
  [ 66  86 103]
  ...
  [ 78  98 115]
  [ 79 100 118]
  [ 79 101 119]]

 [[ 70  92 108]
  [ 68  89 106]
  [ 69  89 106]
  ...
  [ 74  93 110]
  [ 75  96 113]
  [ 73  95 112]]

 ...

 [[ 45  41  62]
  [ 53  42  61]
  [ 65  45  61]
  ...
  [ 64  80  96]
  [ 65  81  97]
  [ 65  81  98]]

 [[ 24  31  55]
  [ 32  34  58]
  [ 44  37  59]
  ...
  [ 71  86 102]
  [ 70  86 102]
  [ 68  84 101]]

 [[ 12  21  49]
  [ 15  24  52]
  [ 19  24  51]
  ...
  [ 54  68  84]
  [ 60  74  90]
  [ 66  81  98]]]


In [10]:
gray_img=cv2.cvtColor(resized_img,cv2.COLOR_BGR2GRAY)
gray_img2=cv2.cvtColor(resized_img2,cv2.COLOR_BGR2GRAY)
cv2.imshow("ID",gray_img)
cv2.imshow("IDW",gray_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()
                    

In [11]:
gray_img.shape

(3, 4)

In [12]:

print(gray_img)

[[192 183 187 193]
 [189 156 160 189]
 [179 156 159 174]]


In [13]:
np.mean(gray_img,axis=0)

array([186.66666667, 165.        , 168.66666667, 185.33333333])

In [14]:
gray_img2.shape

(400, 400)

In [15]:
print("THIS IS THE 2D MATRIX OF ID")
print('\n')
print(gray_img)
print('\n')
print("THIS IS THE 2D MATRIX OF IDW")
print('\n')
print(gray_img2)

THIS IS THE 2D MATRIX OF ID


[[192 183 187 193]
 [189 156 160 189]
 [179 156 159 174]]


THIS IS THE 2D MATRIX OF IDW


[[ 86  88  90 ... 101  99 102]
 [ 90  89  89 ... 101 103 104]
 [ 94  92  92 ...  96  99  98]
 ...
 [ 48  49  52 ...  83  84  84]
 [ 37  41  44 ...  89  89  87]
 [ 28  31  32 ...  71  77  84]]
